Topic 2: Test Driven Development
hherminioandres/java-bootcamp pull request #4
Opened 2018-07-18 18:51 UTC by hherminioandres

1 - Use TDD to create the 'Recent file list' behaviour. Some examples of this behaviour is:
-When the program is run for the first time, the list is empty.
-When a file is opened, it is added to the recent file list.
-If an opened file already exists in the recent file list, it is bumped to the top, not duplicated in the list.
-If the recent file list gets full (typical number of items is 15), the oldest item is removed when a new item is added.
2 - Using TDD techniques such as mocking, faking and stubs, try to develop your own blog software featuring:
-Post new entry
-Delete existing entry
-Show 10 most recent entries

2018-07-20 18:16 UTC, salaesp requested changes

2018-07-20 18:16 UTC, salaesp commented on src/test/java/com/blog/BlogTest.java
> +		when(blogMock.getPost(NAMEP)).thenReturn(post);
since you are testing the blog, you shouldnt mock it

2018-07-20 18:16 UTC, salaesp commented on src/test/java/com/blog/BlogTest.java
> +	}
you are not testing getting the last X posts.

2018-07-25 03:44 UTC, carlos-lopez-glb approved these changes

2018-07-25 15:45 UTC, merged